# Generated by Django 5.2.6 on 2025-12-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=2)),
                ('occupied', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.student')),
            ],
        ),
    ]
