# Generated by Django 5.2.6 on 2025-12-30 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0002_room_roomallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.student'),
        ),
        migrations.AddIndex(
            model_name='roomallocation',
            index=models.Index(fields=['student', 'is_active'], name='hostel_api__student_d71bfa_idx'),
        ),
    ]
