# Generated by Django 5.2.6 on 2026-01-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0003_alter_roomallocation_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fee', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('effective_from', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.roomallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.student')),
            ],
        ),
    ]
