# Generated by Django 5.2.6 on 2026-01-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0005_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostel_api.room'),
        ),
    ]
