# Generated by Django 5.2.6 on 2026-01-12 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0008_studentqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentqr',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qr_codes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentqr',
            name='valid_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentqr',
            unique_together={('student', 'valid_date')},
        ),
    ]
