# Generated by Django 5.2.6 on 2026-01-12 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0009_studentqr_image_studentqr_valid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqr',
            name='valid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
