# Generated by Django 5.2.6 on 2026-01-15 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0010_alter_studentqr_valid_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelfeeconfig',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='hostelfeeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GateEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_date', models.DateField()),
                ('action', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='ENTRY', max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_api.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'scan_date'], name='hostel_api__student_503cad_idx')],
            },
        ),
    ]
